---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prometheus-operator
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/prometheus-operator/prometheus-operator.git
